declare module '@heroicons/react/outline' {
  import { ComponentType, SVGProps } from 'react'
  
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalendarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CogIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClockIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InformationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LocationMarkerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockClosedIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LogoutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LoginIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RefreshIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExternalLinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShareIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BellIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentTextIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCopyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PrinterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudUploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ServerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DatabaseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TerminalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QrcodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScaleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartLineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartPieIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartSquareBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeTransparentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ColorSwatchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BadgeCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MoonIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SunIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BeakerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BookOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AcademicCapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LibraryIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const NewspaperIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AnnotationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UsersIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserGroupIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const IdentificationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const OfficeBuildingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt1Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt4Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlayIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PauseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StopIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RewindIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FastForwardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MusicNoteIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VideoCameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MicrophoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOnlineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOfflineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const WifiIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RssIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TranslateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArchiveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReplyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QuestionMarkCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BanIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperClipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperAirplaneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapPinIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CompassIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CursorClickIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneMissedCallIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIncomingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneOutgoingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SupportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingBagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TicketIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptRefundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptTaxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyEuroIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyPoundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyRupeeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyYenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalculatorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScissorsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PuzzleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightBulbIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpandIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpand: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewBoardsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TableIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TemplateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusSmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusSmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QuestionMarkCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InformationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BanIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockClosedIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RefreshIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReplyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RewindIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FastForwardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExternalLinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShareIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentTextIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentReportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentSearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCopyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperClipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperAirplaneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PrinterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveAsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScissorsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VideoCameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MusicNoteIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ColorSwatchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArchiveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BellIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AnnotationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const SpeakerphoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MicrophoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIncomingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneOutgoingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneMissedCallIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlayIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PauseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StopIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TranslateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapPinIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LocationMarkerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CompassIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CursorClickIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ServerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TerminalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QrcodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DatabaseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudUploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BeakerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BookOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AcademicCapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LibraryIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const NewspaperIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt1Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt4Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewBoardsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TableIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TemplateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PuzzleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeTransparentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserGroupIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UsersIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const IdentificationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BadgeCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const OfficeBuildingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SupportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightBulbIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SunIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MoonIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalculatorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyEuroIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyPoundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyRupeeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyYenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptRefundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptTaxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingBagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TicketIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TruckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartPieIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartSquareBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartLineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScaleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const WifiIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RssIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOnlineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOfflineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LoginIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LogoutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClockIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalendarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CogIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const Cog6ToothIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpandIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SelectorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const Bars3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const XMarkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotoIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightOnRectangleIcon: ComponentType<SVGProps<SVGSVGElement>>
}

declare module '@heroicons/react/24/outline' {
  import { ComponentType, SVGProps } from 'react'
  
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalendarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CogIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClockIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InformationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LocationMarkerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockClosedIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LogoutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LoginIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RefreshIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExternalLinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShareIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BellIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentTextIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCopyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PrinterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudUploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ServerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DatabaseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TerminalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QrcodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScaleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartLineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartPieIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartSquareBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeTransparentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ColorSwatchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BadgeCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MoonIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SunIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BeakerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BookOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AcademicCapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LibraryIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const NewspaperIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AnnotationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UsersIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserGroupIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const IdentificationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const OfficeBuildingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt1Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt4Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlayIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PauseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StopIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RewindIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FastForwardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MusicNoteIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VideoCameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MicrophoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOnlineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOfflineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const WifiIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RssIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TranslateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArchiveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReplyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QuestionMarkCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BanIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperClipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperAirplaneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapPinIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CompassIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CursorClickIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneMissedCallIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIncomingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneOutgoingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SupportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingBagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TicketIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptRefundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptTaxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyEuroIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyPoundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyRupeeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyYenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalculatorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScissorsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PuzzleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightBulbIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpandIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpand: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewBoardsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TableIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TemplateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlusSmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MinusSmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const XCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CheckCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExclamationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QuestionMarkCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InformationCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShieldExclamationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BanIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockClosedIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LockOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EyeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RefreshIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DotsVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDoubleDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChevronDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowCircleDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowLeftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowRightIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowNarrowDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchHorizontalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SwitchVerticalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReplyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RewindIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FastForwardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ExternalLinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShareIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentTextIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentReportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentSearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DocumentDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardCopyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClipboardListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperClipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PaperAirplaneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PrinterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DuplicateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PencilAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SaveAsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScissorsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LinkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotographIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VideoCameraIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MusicNoteIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilmIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ColorSwatchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArchiveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FolderDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const InboxInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MailOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BellIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AnnotationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChatAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const SpeakerphoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MicrophoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneIncomingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneOutgoingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhoneMissedCallIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const VolumeOffIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PlayIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PauseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StopIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TranslateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GlobeAltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MapPinIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LocationMarkerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CompassIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CursorClickIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DesktopComputerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceMobileIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DeviceTabletIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ServerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TerminalIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const QrcodeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DatabaseIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChipIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudDownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CloudUploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightningBoltIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BeakerIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BookOpenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AcademicCapIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LibraryIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const NewspaperIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt1Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt2Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const MenuAlt4Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewListIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewBoardsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TableIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TemplateIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PuzzleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CubeTransparentIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserCircleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserGroupIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UserRemoveIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UsersIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const IdentificationIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const BadgeCheckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const OfficeBuildingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HomeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SupportIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SparklesIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FireIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const HeartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiHappyIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const EmojiSadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ThumbDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LightBulbIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SunIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const MoonIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const GiftIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalculatorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyDollarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyEuroIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyPoundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyRupeeIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CurrencyYenIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CreditCardIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CashIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptRefundIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ReceiptTaxIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingBagIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ShoppingCartIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TicketIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TruckIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartPieIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ChartSquareBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartBarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PresentationChartLineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingUpIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const TrendingDownIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ScaleIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const WifiIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const RssIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOnlineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const StatusOfflineIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LoginIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const LogoutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const UploadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const DownloadIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ClockIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CalendarIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const CogIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const Cog6ToothIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const AdjustmentsIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const FilterIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortAscendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SortDescendingIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SearchIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomInIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ZoomOutIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ViewGridAddIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowsExpandIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const SelectorIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const Bars3Icon: ComponentType<SVGProps<SVGSVGElement>>
  export const XMarkIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const PhotoIcon: ComponentType<SVGProps<SVGSVGElement>>
  export const ArrowRightOnRectangleIcon: ComponentType<SVGProps<SVGSVGElement>>
}
